[package]
name = "updog"
version = "0.1.0"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[features]
fips = ["tough/fips", "aws-lc-rs/fips"]

[dependencies]
async-trait.workspace = true
argh.workspace = true
aws-lc-rs = { workspace = true, features = ["bindgen"] }
bottlerocket-release.workspace = true
bytes.workspace = true
chrono = { workspace = true, features = ["clock", "std"] }
futures = { workspace = true, features = ["default"] }
futures-core.workspace = true
log.workspace = true
lz4.workspace = true
semver.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_plain.workspace = true
signpost.workspace = true
simplelog.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "process", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["compat", "io-util"] }
toml.workspace = true
tough = { workspace = true, features = ["http"] }
update_metadata.workspace = true
url.workspace = true
signal-hook.workspace = true
bottlerocket-modeled-types.workspace = true

[dev-dependencies]
tempfile.workspace = true
